on:
  pull_request:
  push:
    branches: main
name: Linkinator
jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "**/*.md*"
          markdown: true
          recurse: true
          linksToSkip: "https://opensea.io, http://localhost:3000, assets/, /assets, https://support.discord.com, https://www.pokemoncenter.com"
